Repository jenkins-infra/update-center2, pull requests merged in 2020-12, with the labels that each got.

#473 [INFRA-2838] Block broken releases of nexus-jenkins-plugin
  resources/artifact-ignores.properties
Labels: metadata

#471 Stop overriding the expected validity duration of the signing cert
  site/generate.sh
Labels: wrapper

#476 Add support for snapshot versions
  site/generate-htaccess.sh
  site/test/test.sh
Labels: bugfix, wrapper

#474 SECURITY-157 is fixed in mask-passwords 2.13.0
  resources/warnings.json
Labels: metadata

#475 Restore distribution of tics plugin with fixed dependencies
  resources/artifact-ignores.properties
Labels: metadata

#477 SECURITY-829 ircbot fixed in 2.36
  resources/warnings.json
Labels: metadata

#472 issue [SECURITY-1460] was fixed version 3.6.6
  resources/warnings.json
Labels: metadata
