Repository jenkins-infra/update-center2, pull requests merged in 2020-08, with the labels that each got.

#387 Update dependencies
  pom.xml
Labels: enhancement

#411 Suspend distribution of sideex-1.0.0
  resources/artifact-ignores.properties
Labels: metadata

#410 Update to 3.3.1
  site/generate.sh
Labels: enhancement, on-hold

#413 Close PEMReader
  src/main/java/io/jenkins/update_center/Signer.java
Labels: bugfix

#414 Fix Javadoc warnings
  src/main/java/io/jenkins/update_center/DirectoryTreeBuilder.java
  src/main/java/io/jenkins/update_center/HPI.java
  src/main/java/io/jenkins/update_center/MavenArtifact.java
  src/main/java/io/jenkins/update_center/MavenRepository.java
  src/main/java/io/jenkins/update_center/Plugin.java
  src/main/java/io/jenkins/update_center/Signer.java
  src/main/java/io/jenkins/update_center/json/WithSignature.java
Labels: bugfix

#416 Nest dynamic tier directories into common top-level directory
  site/README.md
  site/generate-htaccess.sh
  site/generate.sh
  site/static/dynamic.html
  site/test/test.sh
Labels: enhancement, wrapper

#417 Identify which plugin releases have non-existing core dependencies
  src/main/java/io/jenkins/update_center/json/TieredUpdateSitesGenerator.java
Labels: enhancement

#419 Cleaner tool invocation, easier to substitute
  site/generate.sh
Labels: enhancement, wrapper

#420 Revert "Nest dynamic tier directories into common top-level directory"
  site/README.md
  site/generate-htaccess.sh
  site/generate.sh
  site/static/dynamic.html
  site/test/test.sh
Labels: bugfix, wrapper

#405 Update artifact-ignores.properties
  resources/artifact-ignores.properties
  resources/label-definitions.properties
Labels: metadata

#392 Suspend distribution of fortify-cloudscan-jenkins-plugin, add deprecation URL
  resources/artifact-ignores.properties
  resources/deprecations.properties
Labels: metadata

#426 Properly mark sonargraph-plugin as deprecated
  resources/deprecations.properties
  resources/label-definitions.properties
Labels: metadata

#427 Note references to various directory indexes
  site/LAYOUT.md
  src/main/java/io/jenkins/update_center/DirectoryTreeBuilder.java
Labels: documentation

#435 Add redis to allowed-github-topics
  resources/allowed-github-topics.properties
Labels: metadata

#418 [INFRA-2615] Deprecate fixed tiers, don't generate for 2.249.x+
  site/generate.sh
Labels: enhancement, wrapper
