Repository jenkins-infra/update-center2, pull requests merged in 2020-09, with the labels that each got.

#443 Include next higher LTS as a baseline for weekly dependencies
  src/main/java/io/jenkins/update_center/json/TieredUpdateSitesGenerator.java
Labels: bugfix

#439 [SECURITY-1630] Update versions regex
  resources/warnings.json
Labels: metadata

#397 [SECURITY-1686] Disable warning for 2.5.1+
  resources/warnings.json
Labels: metadata

#408 Added "devsecops" category
  resources/allowed-github-topics.properties
Labels: metadata, on-hold

#444 [INFRA-2622] Selectively suspend old liquibase-runner for licensing i…
  resources/artifact-ignores.properties
Labels: metadata, on-hold

#383 [SECURITY-519] Disable liquibase-runner security warning
  resources/warnings.json
Labels: metadata
