Repository jenkins-infra/update-center2, pull requests merged in 2020-05, with the labels that each got.

#367 Add readme for deprected plugin (pipeline-model-declarative-agent)
  src/main/resources/wiki-overrides.properties
Labels: on-hold

#344 [JENKINS-59136] Deprecation support
  README.adoc
  resources/deprecations.properties
  src/main/java/io/jenkins/update_center/Deprecations.java
  src/main/java/io/jenkins/update_center/json/UpdateCenterDeprecation.java
  src/main/java/io/jenkins/update_center/json/UpdateCenterRoot.java
Labels: enhancement

#378 Reuse this regex for all instances of the class
  src/main/java/io/jenkins/update_center/HPI.java
Labels: enhancement

#362 [SECURITY-814] Update pattern after fix in 0.6
  resources/warnings.json
Labels: metadata, on-hold
