Repository jenkins-infra/update-center2, pull requests merged in 2021-04, with the labels that each got.

#514 Fix version range for 2.286 security warning
  resources/warnings.json
Labels: metadata

#509 Note fix of SECURITY-1510 in backlog plugin
  resources/warnings.json
Labels: metadata

#506 SECURITY-1928: fixed in release-plugin 2.11
  resources/warnings.json
Labels: metadata, on-hold

#504 Remove unused GitHub cache
  src/main/java/io/jenkins/update_center/GitHubSource.java
Labels: enhancement

#498 [INFRA-2937] Add support for generating platform-plugins.json
  resources/platform-plugins.json
  src/main/java/io/jenkins/update_center/Main.java
  src/main/java/io/jenkins/update_center/json/PlatformCategory.java
  src/main/java/io/jenkins/update_center/json/PlatformPlugin.java
  src/main/java/io/jenkins/update_center/json/PlatformPluginsRoot.java
Labels: enhancement

#500 Include expected download file size in update-center.json
  src/main/java/io/jenkins/update_center/ArtifactCoordinates.java
  src/main/java/io/jenkins/update_center/ArtifactoryRepositoryImpl.java
  src/main/java/io/jenkins/update_center/BaseMavenRepository.java
  src/main/java/io/jenkins/update_center/HPI.java
  src/main/java/io/jenkins/update_center/IndexHtmlBuilder.java
  src/main/java/io/jenkins/update_center/MavenArtifact.java
  src/main/java/io/jenkins/update_center/MavenRepository.java
  src/main/java/io/jenkins/update_center/Plugin.java
  src/main/java/io/jenkins/update_center/PluginUpdateCenterEntry.java
  src/main/java/io/jenkins/update_center/json/PluginVersionsEntry.java
  src/main/java/io/jenkins/update_center/json/ReleaseHistoryEntry.java
  src/main/java/io/jenkins/update_center/json/TieredUpdateSitesGenerator.java
  src/main/java/io/jenkins/update_center/json/UpdateCenterCore.java
  src/main/java/io/jenkins/update_center/wrappers/MavenRepositoryWrapper.java
  src/test/java/io/jenkins/update_center/MaintainersSourceTest.java
  src/test/java/io/jenkins/update_center/PluginTest.java
  src/test/java/io/jenkins/update_center/util/JavaVersionPluginFilterTest.java
Labels: enhancement

#516 Add generation timestamp to metadata
  src/main/java/io/jenkins/update_center/json/WithSignature.java
  src/test/java/io/jenkins/update_center/TimestampTest.java
Labels: enhancement
