Repository jenkins-infra/update-center2, pull requests merged in 2021-06, with the labels that each got.

#469 Use template for download pages
  pom.xml
  resources/index-template.html
  site/generate.sh
  src/main/java/io/jenkins/update_center/DirectoryTreeBuilder.java
  src/main/java/io/jenkins/update_center/IndexHtmlBuilder.java
  src/main/java/io/jenkins/update_center/IndexTemplateProvider.java
  src/main/java/io/jenkins/update_center/JenkinsIndexTemplateProvider.java
  src/main/java/io/jenkins/update_center/LatestLinkBuilder.java
Labels: enhancement

#523 remove ci-with-toad-edge from list of suspended plugin and suspend specific plugin versions
  resources/artifact-ignores.properties
Labels: metadata

#525 Formally deprecating plugins left behind in recent core PRs
  resources/deprecations.properties
Labels: metadata

#515 SECURITY-1058 was resolved in nomad plugin 0.6.2
  resources/warnings.json
Labels: metadata, on-hold

#518 Note SECURITY-832 being fixed in snsnotify 2.0
  resources/warnings.json
Labels: metadata

#526 [INFRA-2997] Restore zap-pipeline
  resources/artifact-ignores.properties
  resources/warnings.json
Labels: metadata

#528 Set SpotBugs threshold to low, address issues
  pom.xml
  src/main/java/io/jenkins/update_center/DefaultMavenRepositoryBuilder.java
  src/main/java/io/jenkins/update_center/GitHubSource.java
  src/main/java/io/jenkins/update_center/HPI.java
  src/main/java/io/jenkins/update_center/IssueTrackerSource.java
  src/main/java/io/jenkins/update_center/MaintainersSource.java
  src/main/java/io/jenkins/update_center/PluginUpdateCenterEntry.java
Labels: enhancement
