Repository jenkins-infra/update-center2, pull requests merged in 2021-03, with the labels that each got.

#482 Replace obsolete terminology
  README.adoc
  resources/allowed-github-topics.properties
  resources/warnings.json
  site/LAYOUT.md
  src/main/java/io/jenkins/update_center/Main.java
  src/main/java/io/jenkins/update_center/wrappers/AllowedArtifactsListMavenRepository.java
Labels: bugfix

#468 Keep older ambiguous releases
  resources/artifact-ignores.properties
  src/main/java/io/jenkins/update_center/Plugin.java
  src/test/java/io/jenkins/update_center/PluginTest.java
Labels: enhancement

#488 Ignore ca-mat-performance-benchmarking-by-broadcom-1.2
  resources/artifact-ignores.properties
Labels: metadata

#489 Issue [SECURITY-1763] was fixed in version 1.1.0
  resources/warnings.json
Labels: metadata

#490 Fix link in README
  README.adoc
Labels: documentation

#493 Add changelog, document back to 3.0
  CHANGELOG.adoc
Labels: documentation

#492 [INFRA-2928] Add issue tracker metadata
  README.adoc
  src/main/java/io/jenkins/update_center/IssueTrackerSource.java
  src/main/java/io/jenkins/update_center/PluginUpdateCenterEntry.java
Labels: enhancement

#495 [INFRA-2929] Expose default branch in GitHub
  README.adoc
  src/main/java/io/jenkins/update_center/GitHubSource.java
  src/main/java/io/jenkins/update_center/HPI.java
  src/main/java/io/jenkins/update_center/PluginUpdateCenterEntry.java
  src/test/java/io/jenkins/update_center/GitHubSourceTest.java
  src/test/resources/github_graphql_Y3Vyc29yOnYyOpHOA0oRaA==.txt
  src/test/resources/github_graphql_null.txt
Labels: enhancement

#497 Allow overriding max age for recent releases
  site/generate.sh
  src/main/java/io/jenkins/update_center/json/RecentReleasesRoot.java
Labels: enhancement

#499 Use version 3.6, update changelog
  CHANGELOG.adoc
  site/generate.sh
Labels: documentation, wrapper

#501 Return a tiny response for ?uctest requests
  site/generate-htaccess.sh
  site/generate.sh
  site/test/Dockerfile
  site/test/test.sh
Labels: wrapper

#502 Use RPU permissions for 'developers' instead of Maven metadata
  README.adoc
  src/main/java/io/jenkins/update_center/HPI.java
  src/main/java/io/jenkins/update_center/MaintainersSource.java
  src/main/java/io/jenkins/update_center/PluginUpdateCenterEntry.java
  src/test/java/io/jenkins/update_center/MaintainersSourceTest.java
Labels: enhancement

#505 SECURITY-1559 was fixed in digitalocean-plugin-1.2.0
  resources/warnings.json
Labels: on-hold

#507 [INFRA-1502] Perform validation with new root certificate
  site/generate.sh
Labels: bugfix, wrapper
