Repository jenkins-infra/update-center2, pull requests merged in 2022-08, with the labels that each got.

#620 Replace broken wiki short URLs with full URLs
  resources/artifact-ignores.properties
Labels: metadata

#627 [SECURITY-2220] Fixed by plot 2.1.11
  resources/warnings.json
Labels: metadata

#628 [SECURITY-2053] Fixed by http_request plugin 1.16
  resources/warnings.json
Labels: metadata

#569 Simplify symlink creation, update dependencies
  pom.xml
  spotbugs-excludes.xml
  src/main/java/io/jenkins/update_center/ArtifactoryRepositoryImpl.java
  src/main/java/io/jenkins/update_center/DirectoryTreeBuilder.java
Labels: enhancement, dependencies

#591 Revert JENKINS-20679
  README.adoc
  src/main/java/io/jenkins/update_center/HPI.java
  src/main/java/io/jenkins/update_center/Main.java
  src/main/java/io/jenkins/update_center/PluginUpdateCenterEntry.java
  src/main/java/io/jenkins/update_center/filters/JavaVersionPluginFilter.java
  src/main/java/io/jenkins/update_center/util/JavaSpecificationVersion.java
  src/test/java/ListPluginsAndVersionsJava6.java
  src/test/java/io/jenkins/update_center/util/JavaSpecificationVersionTest.java
  src/test/java/io/jenkins/update_center/util/JavaVersionPluginFilterTest.java
Labels: enhancement

#532 Handle duplicate maintainer entries
  src/main/java/io/jenkins/update_center/HPI.java
  src/main/java/io/jenkins/update_center/MaintainersSource.java
Labels: enhancement

#554 Discard hpi/jpi/war artifacts without corresponding pom file
  src/main/java/io/jenkins/update_center/ArtifactoryRepositoryImpl.java
Labels: enhancement

#561 --id parameter from CLI is ignored
  src/main/java/io/jenkins/update_center/Main.java
  src/main/java/io/jenkins/update_center/json/UpdateCenterRoot.java
Labels: bugfix

#635 Do not wipe options with default values when using --arguments-file
  src/main/java/io/jenkins/update_center/Main.java
  src/main/java/io/jenkins/update_center/args4j/Default.java
Labels: bugfix

#612 Print the core dependency version
  resources/index-template.html
  src/main/java/io/jenkins/update_center/IndexHtmlBuilder.java
Labels: enhancement

#636 Add 'releaseTimestamp' with second resolution to plugin-versions.json
  src/main/java/io/jenkins/update_center/json/PluginVersionsEntry.java
Labels: enhancement
