Repository jenkins-infra/update-center2, pull requests merged in 2023-08, with the labels that each got.

#728 Remove SECURITY-1450 for v3+ releases - Updated regex pattern
  resources/warnings.json
Labels: metadata

#732 Suspend Azure Dev Spaces plugin, service discontinued
  resources/artifact-ignores.properties
Labels: needs-fix, metadata

#730 Remove SECURITY-2892 warning from TestComplete
  resources/warnings.json
Labels: on-hold, metadata
