Repository jenkins-infra/update-center2, pull requests merged in 2024-10, with the labels that each got.

#808 Revert "Suspend `shared-library-version-override`"
  resources/artifact-ignores.properties
  resources/warnings.json
Labels: metadata

#812 fix(site/htaccess) only use Apache `mod_rewrite` by replacing `RedirectMatch` by `RewriteRule` directives
  site/generate-htaccess.sh
  site/publish.sh
  site/test/test.sh
Labels: wrapper

#810 Use absolute URLs for links from download indexes
  src/main/java/io/jenkins/update_center/DirectoryTreeBuilder.java
  src/main/java/io/jenkins/update_center/IndexHtmlBuilder.java
Labels: enhancement, java
