Repository jenkins-infra/update-center2, pull requests merged in 2024-03, with the labels that each got.

#763 [SECURITY-2716] Update warning range as the fix went into 0.0.8
  resources/warnings.json
Labels: metadata

#686 Further limit allowed characters in file path
  src/main/java/io/jenkins/update_center/ArtifactoryRepositoryImpl.java
Labels: enhancement

#697 sort according to VersionNumber comparator
  src/main/java/io/jenkins/update_center/json/PluginVersions.java
Labels: enhancement

#766 Fix GitHub authentication
  src/main/java/io/jenkins/update_center/GitHubSource.java
Labels: bugfix

#687 Make it easier to use with custom repositories
  src/main/java/io/jenkins/update_center/ArtifactoryRepositoryImpl.java
Labels: enhancement

#745 Also sync content into Azure File Share and R2 buckets
  site/publish.sh
Labels: wrapper
